# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
